//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from ./RenDisco/Renpy.g4 by ANTLR 4.13.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419


  using AntlrDenter;

using System;
using System.IO;
using System.Text;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.2")]
[System.CLSCompliant(false)]
public partial class RenpyLexer : Lexer {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		T__0=1, T__1=2, T__2=3, T__3=4, T__4=5, T__5=6, T__6=7, T__7=8, T__8=9, 
		T__9=10, T__10=11, IDENT=12, STRING=13, FLOAT=14, INT=15, NL=16, WS=17, 
		LINE_COMMENT=18;
	public static string[] channelNames = {
		"DEFAULT_TOKEN_CHANNEL", "HIDDEN"
	};

	public static string[] modeNames = {
		"DEFAULT_MODE"
	};

	public static readonly string[] ruleNames = {
		"T__0", "T__1", "T__2", "T__3", "T__4", "T__5", "T__6", "T__7", "T__8", 
		"T__9", "T__10", "IDENT", "STRING", "FLOAT", "INT", "NL", "WS", "LINE_COMMENT"
	};


	  private DenterHelper denter;

	  public override IToken NextToken()
	  {
	    if (denter == null)
	    {
	      denter = DenterHelper.Builder()
	        .Nl(NL)
	        .Indent(RenpyParser.INDENT)
	        .Dedent(RenpyParser.DEDENT)
	        .PullToken(base.NextToken);
	    }

	    return denter.NextToken();
	  }


	public RenpyLexer(ICharStream input)
	: this(input, Console.Out, Console.Error) { }

	public RenpyLexer(ICharStream input, TextWriter output, TextWriter errorOutput)
	: base(input, output, errorOutput)
	{
		Interpreter = new LexerATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}

	private static readonly string[] _LiteralNames = {
		null, "':'", "'='", "'('", "')'", "'bg'", "'+'", "'-'", "'*'", "'/'", 
		"'<'", "'>'"
	};
	private static readonly string[] _SymbolicNames = {
		null, null, null, null, null, null, null, null, null, null, null, null, 
		"IDENT", "STRING", "FLOAT", "INT", "NL", "WS", "LINE_COMMENT"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "Renpy.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override string[] ChannelNames { get { return channelNames; } }

	public override string[] ModeNames { get { return modeNames; } }

	public override int[] SerializedAtn { get { return _serializedATN; } }

	static RenpyLexer() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}
	private static int[] _serializedATN = {
		4,0,18,128,6,-1,2,0,7,0,2,1,7,1,2,2,7,2,2,3,7,3,2,4,7,4,2,5,7,5,2,6,7,
		6,2,7,7,7,2,8,7,8,2,9,7,9,2,10,7,10,2,11,7,11,2,12,7,12,2,13,7,13,2,14,
		7,14,2,15,7,15,2,16,7,16,2,17,7,17,1,0,1,0,1,1,1,1,1,2,1,2,1,3,1,3,1,4,
		1,4,1,4,1,5,1,5,1,6,1,6,1,7,1,7,1,8,1,8,1,9,1,9,1,10,1,10,1,11,1,11,5,
		11,63,8,11,10,11,12,11,66,9,11,1,12,1,12,5,12,70,8,12,10,12,12,12,73,9,
		12,1,12,1,12,1,13,4,13,78,8,13,11,13,12,13,79,1,13,1,13,4,13,84,8,13,11,
		13,12,13,85,3,13,88,8,13,1,13,1,13,4,13,92,8,13,11,13,12,13,93,3,13,96,
		8,13,1,14,4,14,99,8,14,11,14,12,14,100,1,15,3,15,104,8,15,1,15,1,15,5,
		15,108,8,15,10,15,12,15,111,9,15,1,16,4,16,114,8,16,11,16,12,16,115,1,
		16,1,16,1,17,1,17,5,17,122,8,17,10,17,12,17,125,9,17,1,17,1,17,1,71,0,
		18,1,1,3,2,5,3,7,4,9,5,11,6,13,7,15,8,17,9,19,10,21,11,23,12,25,13,27,
		14,29,15,31,16,33,17,35,18,1,0,5,3,0,65,90,95,95,97,122,4,0,48,57,65,90,
		95,95,97,122,1,0,48,57,2,0,9,9,32,32,2,0,10,10,13,13,139,0,1,1,0,0,0,0,
		3,1,0,0,0,0,5,1,0,0,0,0,7,1,0,0,0,0,9,1,0,0,0,0,11,1,0,0,0,0,13,1,0,0,
		0,0,15,1,0,0,0,0,17,1,0,0,0,0,19,1,0,0,0,0,21,1,0,0,0,0,23,1,0,0,0,0,25,
		1,0,0,0,0,27,1,0,0,0,0,29,1,0,0,0,0,31,1,0,0,0,0,33,1,0,0,0,0,35,1,0,0,
		0,1,37,1,0,0,0,3,39,1,0,0,0,5,41,1,0,0,0,7,43,1,0,0,0,9,45,1,0,0,0,11,
		48,1,0,0,0,13,50,1,0,0,0,15,52,1,0,0,0,17,54,1,0,0,0,19,56,1,0,0,0,21,
		58,1,0,0,0,23,60,1,0,0,0,25,67,1,0,0,0,27,95,1,0,0,0,29,98,1,0,0,0,31,
		103,1,0,0,0,33,113,1,0,0,0,35,119,1,0,0,0,37,38,5,58,0,0,38,2,1,0,0,0,
		39,40,5,61,0,0,40,4,1,0,0,0,41,42,5,40,0,0,42,6,1,0,0,0,43,44,5,41,0,0,
		44,8,1,0,0,0,45,46,5,98,0,0,46,47,5,103,0,0,47,10,1,0,0,0,48,49,5,43,0,
		0,49,12,1,0,0,0,50,51,5,45,0,0,51,14,1,0,0,0,52,53,5,42,0,0,53,16,1,0,
		0,0,54,55,5,47,0,0,55,18,1,0,0,0,56,57,5,60,0,0,57,20,1,0,0,0,58,59,5,
		62,0,0,59,22,1,0,0,0,60,64,7,0,0,0,61,63,7,1,0,0,62,61,1,0,0,0,63,66,1,
		0,0,0,64,62,1,0,0,0,64,65,1,0,0,0,65,24,1,0,0,0,66,64,1,0,0,0,67,71,5,
		34,0,0,68,70,9,0,0,0,69,68,1,0,0,0,70,73,1,0,0,0,71,72,1,0,0,0,71,69,1,
		0,0,0,72,74,1,0,0,0,73,71,1,0,0,0,74,75,5,34,0,0,75,26,1,0,0,0,76,78,7,
		2,0,0,77,76,1,0,0,0,78,79,1,0,0,0,79,77,1,0,0,0,79,80,1,0,0,0,80,87,1,
		0,0,0,81,83,5,46,0,0,82,84,7,2,0,0,83,82,1,0,0,0,84,85,1,0,0,0,85,83,1,
		0,0,0,85,86,1,0,0,0,86,88,1,0,0,0,87,81,1,0,0,0,87,88,1,0,0,0,88,96,1,
		0,0,0,89,91,5,46,0,0,90,92,7,2,0,0,91,90,1,0,0,0,92,93,1,0,0,0,93,91,1,
		0,0,0,93,94,1,0,0,0,94,96,1,0,0,0,95,77,1,0,0,0,95,89,1,0,0,0,96,28,1,
		0,0,0,97,99,7,2,0,0,98,97,1,0,0,0,99,100,1,0,0,0,100,98,1,0,0,0,100,101,
		1,0,0,0,101,30,1,0,0,0,102,104,5,13,0,0,103,102,1,0,0,0,103,104,1,0,0,
		0,104,105,1,0,0,0,105,109,5,10,0,0,106,108,5,32,0,0,107,106,1,0,0,0,108,
		111,1,0,0,0,109,107,1,0,0,0,109,110,1,0,0,0,110,32,1,0,0,0,111,109,1,0,
		0,0,112,114,7,3,0,0,113,112,1,0,0,0,114,115,1,0,0,0,115,113,1,0,0,0,115,
		116,1,0,0,0,116,117,1,0,0,0,117,118,6,16,0,0,118,34,1,0,0,0,119,123,5,
		35,0,0,120,122,8,4,0,0,121,120,1,0,0,0,122,125,1,0,0,0,123,121,1,0,0,0,
		123,124,1,0,0,0,124,126,1,0,0,0,125,123,1,0,0,0,126,127,6,17,0,0,127,36,
		1,0,0,0,13,0,64,71,79,85,87,93,95,100,103,109,115,123,1,6,0,0
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
